//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGHAmbulance
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public int ID { get; set; }
        public string EMPLOYEENAME { get; set; }
        public string ADDRESS { get; set; }
        public string CONTACT { get; set; }
        public string DESIGNATION { get; set; }
        public string DEPARTMENT { get; set; }
    }
}
